version: '3.8' 

services:
  database:
    container_name: ffp-api-db
    hostname: ffp-api-postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database